#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# 建立 production 環境：Supabase 專案、Vercel 專案、GitHub secrets。
# 設計與背景見 docs/specs/2026-10-02-production-deployment-design.md。
# 可重複執行；已輸入的值存在 .env.production.local（已被 .gitignore 排除，做完可刪），Enter 沿用。

TOTAL_STAGES=7
ENV_FILE=".env.production.local"
VERCEL_CLI="vercel@62.1.0"
VERCEL_PROJECT_NAME="rpai-course-platform"

cd "$(dirname "$0")/.."

banner "RPAI Course Platform：建立 production 環境"

# ── 1. GitHub 身分 ────────────────────────────────────────────────────────
stage "確認 GitHub 身分（需要 repo owner）"
say "設定 GitHub secrets 需要 repo owner 權限（rpaidevolper）。"
if ! command -v gh >/dev/null 2>&1 || ! gh auth status >/dev/null 2>&1; then
  warn "gh 未安裝或未登入。先執行 gh auth login，再重跑本腳本。"
  exit 1
fi
permission=$(gh repo view --json viewerPermission --jq .viewerPermission 2>/dev/null || echo "UNKNOWN")
if [[ "$permission" != "ADMIN" ]]; then
  warn "目前的 gh 帳號權限是 $permission，不是 ADMIN。"
  if confirm "切換到 rpaidevolper？（需要該帳號已登入 gh）"; then
    gh auth switch -u rpaidevolper
    permission=$(gh repo view --json viewerPermission --jq .viewerPermission)
  fi
  [[ "$permission" == "ADMIN" ]] || { warn "仍然不是 ADMIN，無法設定 secrets，結束。"; exit 1; }
fi
say "✓ 目前帳號有 repo 管理權限"
pause

# ── 2. Supabase 專案 ──────────────────────────────────────────────────────
stage "Supabase：建立 production 專案"
say "這個專案放正式資料。開發者平常用本機 Supabase，不會碰它。"
open_url "https://supabase.com/dashboard/new"
step "Project name 填 rpai-course-platform-production。"
step "Database password 按 Generate，並先存進你的密碼管理器（下一步要貼回來）。"
step "Region 選離講師最近的（台灣用戶建議 Northeast Asia (Tokyo)）。"
step "按 Create new project，等狀態變成可用（約 1–2 分鐘）。"
warn "免費方案沒有自動備份。真實講師資料進來之前，建議升級到有每日備份的方案。"
pause "專案建好了？"
open_url "https://supabase.com/dashboard/project/_/settings/general"
step "在 Settings → General 找到 Reference ID（20 個字元），複製。"
ask SUPABASE_PROJECT_REF "Paste Reference ID:"
ask_secret SUPABASE_DB_PASSWORD "Paste database password:"
write_env SUPABASE_PROJECT_REF "$SUPABASE_PROJECT_REF"
write_env SUPABASE_DB_PASSWORD "$SUPABASE_DB_PASSWORD"
set_secret SUPABASE_PROJECT_REF "$SUPABASE_PROJECT_REF"
set_secret SUPABASE_DB_PASSWORD "$SUPABASE_DB_PASSWORD"

# ── 3. Supabase API keys ──────────────────────────────────────────────────
stage "Supabase：API keys"
say "後台用 anon key（公開）與 service role key（只能放伺服器端）。"
open_url "https://supabase.com/dashboard/project/$SUPABASE_PROJECT_REF/settings/api-keys"
step "anon（或 Publishable）key：複製。"
ask NEXT_PUBLIC_SUPABASE_ANON_KEY "Paste anon / publishable key:"
step "service_role（或 Secret）key：按 Reveal 後複製。這把能繞過 RLS，不要貼到任何聊天或 repo。"
ask_secret SUPABASE_SERVICE_ROLE_KEY "Paste service role / secret key:"
NEXT_PUBLIC_SUPABASE_URL="https://$SUPABASE_PROJECT_REF.supabase.co"
write_env NEXT_PUBLIC_SUPABASE_URL "$NEXT_PUBLIC_SUPABASE_URL"
write_env NEXT_PUBLIC_SUPABASE_ANON_KEY "$NEXT_PUBLIC_SUPABASE_ANON_KEY"
write_env SUPABASE_SERVICE_ROLE_KEY "$SUPABASE_SERVICE_ROLE_KEY"

# ── 4. Supabase access token ──────────────────────────────────────────────
stage "Supabase：Access token（給 CI 套用 migration）"
open_url "https://supabase.com/dashboard/account/tokens"
step "按 Generate new token，名稱填 rpai-course-platform-ci，複製（只會顯示一次）。"
ask_secret SUPABASE_ACCESS_TOKEN "Paste access token:"
write_env SUPABASE_ACCESS_TOKEN "$SUPABASE_ACCESS_TOKEN"
set_secret SUPABASE_ACCESS_TOKEN "$SUPABASE_ACCESS_TOKEN"

# ── 5. Anthropic ──────────────────────────────────────────────────────────
stage "Anthropic：API key（藍圖對話用）"
open_url "https://console.anthropic.com/settings/keys"
step "Create Key，名稱填 rpai-course-platform-production，複製（只會顯示一次）。"
ask_secret ANTHROPIC_API_KEY "Paste Anthropic API key:"
write_env ANTHROPIC_API_KEY "$ANTHROPIC_API_KEY"

# ── 6. Vercel ─────────────────────────────────────────────────────────────
stage "Vercel：建立專案並設定環境變數"
say "專案由 CLI 建立，且不連接 GitHub（部署只由 GitHub Actions 觸發）。"
open_url "https://vercel.com/account/tokens"
step "Create Token，名稱 rpai-course-platform-ci，Scope 選你要放這個專案的 team，到期日自訂。複製（只會顯示一次）。"
ask_secret VERCEL_TOKEN "Paste Vercel token:"
write_env VERCEL_TOKEN "$VERCEL_TOKEN"
say "建立（或連結既有的）Vercel 專案 $VERCEL_PROJECT_NAME …"
npx --yes "$VERCEL_CLI" link --yes --project "$VERCEL_PROJECT_NAME" --token "$VERCEL_TOKEN"
VERCEL_ORG_ID=$(node -p "require('./.vercel/project.json').orgId")
VERCEL_PROJECT_ID=$(node -p "require('./.vercel/project.json').projectId")
[[ -n "$VERCEL_ORG_ID" && -n "$VERCEL_PROJECT_ID" ]] || { warn "讀不到專案 ID，結束。"; exit 1; }
write_env VERCEL_ORG_ID "$VERCEL_ORG_ID"
write_env VERCEL_PROJECT_ID "$VERCEL_PROJECT_ID"
set_secret VERCEL_TOKEN "$VERCEL_TOKEN"
set_secret VERCEL_ORG_ID "$VERCEL_ORG_ID"
set_secret VERCEL_PROJECT_ID "$VERCEL_PROJECT_ID"
say "寫入 Vercel Production 環境變數 …"
for name in ANTHROPIC_API_KEY NEXT_PUBLIC_SUPABASE_URL NEXT_PUBLIC_SUPABASE_ANON_KEY SUPABASE_SERVICE_ROLE_KEY; do
  printf '%s' "${!name}" | npx --yes "$VERCEL_CLI" env add "$name" production --force --token "$VERCEL_TOKEN" >/dev/null
  printf '  %s✓ set%s Vercel env %s (production)\n' "$GREEN" "$RESET" "$name"
done
pause

# ── 7. Production 網址 ────────────────────────────────────────────────────
stage "Production 網址（smoke test 用）"
open_url "https://vercel.com/dashboard"
step "進入 $VERCEL_PROJECT_NAME 專案 → Settings → Domains，找到 production 網址（通常是 ${VERCEL_PROJECT_NAME}.vercel.app）。"
ask PRODUCTION_URL "Paste production URL（含 https://）:"
write_env PRODUCTION_URL "$PRODUCTION_URL"
set_var PRODUCTION_URL "$PRODUCTION_URL"

finish
say "下一步：把這個 PR 合併到 main，然後第一次部署由手動觸發："
say "  gh workflow run deploy.yml --ref main"
say "之後每次合併到 main 都會自動部署。"
say "做完可刪除 $ENV_FILE 與 .vercel/（內含 production 密碼，已被 .gitignore 排除）。"
printf '\n'
